[package]
name = "hub-core"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.28"
embedded-io-async = "0.7.0"
heapless = "0.9.2"
embassy-futures = "0.1.2"

[target.xtensa-esp32s3-none-elf.dependencies]
esp-hal     = { version = "1.0.0-rc.0", features = ["esp32s3", "unstable", "rt"] }
esp-println = { version = "0.16.1", features = ["esp32s3", "log-04"] }
esp-sync    = { version = "0.1.1", features = ["esp32s3"] }
esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32s3"] }
esp-backtrace = { version = "0.18.1", features = ["esp32s3", "panic-handler", "println", "colors"] }
esp-alloc = { version = "0.9.0", default-features = false }
esp-rtos = { version = "0.2.0", features = ["esp32s3", "esp-radio", "esp-alloc", "embassy"] }

# BLE controller
esp-radio = { version = "0.17.0", features = ["esp32s3", "ble", "unstable", "esp-alloc"] }
bt-hci = "0.6" # IMPORTANT: keep bt-hci at 0.6 with trouble-host 0.5.1
trouble-host = { version = "0.5.1", default-features = false, features = [
    "central",
    "gatt",
    "scan",
    "default-packet-pool",
    "default-packet-pool-size-32",
    "default-packet-pool-mtu-251"
] }
static_cell = "2.1.0"
embassy-executor = { version = "0.9.1", default-features = false }
embassy-time     = { version = "0.5.0", default-features = false }

[profile.dev.package.esp-radio]
opt-level = 3

[profile.dev]
opt-level = "s"
panic = "abort"

[profile.release]
opt-level = "s"
panic = "abort"
lto = "fat"
codegen-units = 1

[[bin]]
name = "hub-core-fw"
path = "src/main.rs"
test = false
bench = false