//! NVS-backed persistence for hub identity and credentials.
//!
//! Storage layout (NVS namespace `"hub"`):
//!   - `device_id`  : UUIDv4, lowercase hex with hyphens (36 bytes), generated by `build.rs`.
//!   - `hub_secret` : 32 random bytes hex-encoded (64 bytes), generated by `build.rs`.
//!   - `jwt`        : variable-length hub JWT obtained from `auth.v2.ClaimHubToken`.

use anyhow::{Context, Result};
use esp_idf_svc::nvs::{EspDefaultNvsPartition, EspNvs};
use log::info;

const NAMESPACE: &str = "hub";
const KEY_DEVICE_ID: &str = "device_id";
const KEY_HUB_SECRET: &str = "hub_secret";
const KEY_JWT: &str = "jwt";
const BUILD_DEVICE_ID: &str = env!("HUB_DEVICE_ID");
const BUILD_HUB_SECRET: &str = env!("HUB_SECRET");

/// Returns `(device_id, hub_secret)`. Seeds both from build-time values on first
/// boot, then re-reads them from NVS on subsequent boots.
pub fn load_or_generate_creds(nvs: EspDefaultNvsPartition) -> Result<(String, String)> {
    // Try read first — namespace may not exist yet on a fresh device, which is fine.
    let read_handle = EspNvs::new(nvs.clone(), NAMESPACE, true)
        .context("open NVS namespace 'hub' for read/write")?;

    let existing_id = read_str(&read_handle, KEY_DEVICE_ID)?;
    let existing_secret = read_str(&read_handle, KEY_HUB_SECRET)?;

    if let (Some(id), Some(secret)) = (existing_id, existing_secret) {
        info!("hub creds loaded from NVS (device_id={id})");
        return Ok((id, secret));
    }

    // Either or both keys missing → seed the build-time pair atomically so the
    // setup URI printed by Cargo matches what the firmware persists.
    let device_id = BUILD_DEVICE_ID.to_string();
    let hub_secret = BUILD_HUB_SECRET.to_string();

    read_handle
        .set_str(KEY_DEVICE_ID, &device_id)
        .context("write device_id to NVS")?;
    read_handle
        .set_str(KEY_HUB_SECRET, &hub_secret)
        .context("write hub_secret to NVS")?;

    info!("hub creds seeded from build identity (device_id={device_id})");
    Ok((device_id, hub_secret))
}

pub fn read_hub_jwt(nvs: EspDefaultNvsPartition) -> Result<Option<String>> {
    let handle =
        EspNvs::new(nvs, NAMESPACE, false).context("open NVS namespace 'hub' read-only")?;
    read_str(&handle, KEY_JWT)
}

pub fn write_hub_jwt(nvs: EspDefaultNvsPartition, jwt: &str) -> Result<()> {
    let handle =
        EspNvs::new(nvs, NAMESPACE, true).context("open NVS namespace 'hub' for jwt write")?;
    handle.set_str(KEY_JWT, jwt).context("write jwt to NVS")?;
    Ok(())
}

/// Dev-only override: seed NVS with a JWT supplied at build time via `HUB_TOKEN=…`.
/// Skipped silently if the token already matches what's stored, so reboots stay quiet.
pub fn seed_jwt_from_env(nvs: EspDefaultNvsPartition, token: &str) -> Result<()> {
    if let Some(existing) = read_hub_jwt(nvs.clone())? {
        if existing == token {
            return Ok(());
        }
    }
    write_hub_jwt(nvs, token)?;
    info!("HUB_TOKEN seeded into NVS (dev override)");
    Ok(())
}

/// Read a UTF-8 string from NVS, returning `None` if the key is absent.
///
/// Pattern from esp-idf-svc 0.52.1: `str_len` returns required byte count
/// (including trailing NUL), then `get_str` fills the exact buffer.
fn read_str<P>(handle: &EspNvs<P>, key: &str) -> Result<Option<String>>
where
    P: esp_idf_svc::nvs::NvsPartitionId,
{
    let Some(len) = handle
        .str_len(key)
        .with_context(|| format!("nvs str_len('{key}')"))?
    else {
        return Ok(None);
    };

    let mut buf = vec![0u8; len];
    let value = handle
        .get_str(key, &mut buf)
        .with_context(|| format!("nvs get_str('{key}')"))?
        .map(ToOwned::to_owned);
    Ok(value)
}
